apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # Unique key of the ReplicaSet instance
  name: replicaset-example
  labels:
    type: nginx-rs
spec:
  # 4 Pods should exist at all times.
  # check how the pods are placed between nodes after cordon or edit the node as unschedulable
  replicas: 4
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
